### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by branka5** [madmartin/Jarolift_MQTT#58]
Hi,

I wanted to compile with Arduino 2.0.4. Now I am getting the following error message. Can someone help?

Many thanks

C:\Users\xx\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:66:10: fatal error: PubSubClient.h: No such file or directory
   66 | #include <PubSubClient.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: PubSubClient.h: No such file or directory

**Comment by t4e-dev** [comment]
Hi. Sounds fixable :-)
Please have a look at this page : https://www.programmingelectronics.com/no-such-file-error/#:~:text=The%20easiest%20way%20is%20to,go%20ahead%20and%20click%20Install.

The missing library is probably this one here : https://www.arduino.cc/reference/en/libraries/pubsubclient/

**Comment by branka5** [comment]
Thanks t4e-dev. Your help is highly appreciated. I could fix this issue.

However when I am compiling the Sketch I am getting the following error messages. Can someone guide me through?

In file included from C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:3:
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:30:16: error: variable 'dstRule StartRule' has initializer but incomplete type
   30 | struct dstRule StartRule = {"CEST", Last, Sun, Mar, 2, 3600}; // Daylight time
      |                ^~~~~~~~~
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:30:37: error: 'Last' was not declared in this scope
   30 | struct dstRule StartRule = {"CEST", Last, Sun, Mar, 2, 3600}; // Daylight time
      |                                     ^~~~
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:30:43: error: 'Sun' was not declared in this scope
   30 | struct dstRule StartRule = {"CEST", Last, Sun, Mar, 2, 3600}; // Daylight time
      |                                           ^~~
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:30:48: error: 'Mar' was not declared in this scope
   30 | struct dstRule StartRule = {"CEST", Last, Sun, Mar, 2, 3600}; // Daylight time
      |                                                ^~~
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:31:16: error: variable 'dstRule EndRule' has initializer but incomplete type
   31 | struct dstRule EndRule = {"CET", Last, Sun, Oct, 2, 0};       // Standard time
      |                ^~~~~~~
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:31:34: error: 'Last' was not declared in this scope
   31 | struct dstRule EndRule = {"CET", Last, Sun, Oct, 2, 0};       // Standard time
      |                                  ^~~~
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:31:40: error: 'Sun' was not declared in this scope
   31 | struct dstRule EndRule = {"CET", Last, Sun, Oct, 2, 0};       // Standard time
      |                                        ^~~
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:31:45: error: 'Oct' was not declared in this scope
   31 | struct dstRule EndRule = {"CET", Last, Sun, Oct, 2, 0};       // Standard time
      |                                             ^~~
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:32:1: error: 'simpleDSTadjust' does not name a type
   32 | simpleDSTadjust dstAdjusted(StartRule, EndRule);  // Setup simpleDSTadjust Library rules
      | ^~~~~~~~~~~~~~~
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:34:1: error: 'ESP8266WebServer' does not name a type
   34 | ESP8266WebServer server(80);                      // The Webserver
      | ^~~~~~~~~~~~~~~~
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:35:1: error: 'WiFiClient' does not name a type
   35 | WiFiClient espClient;
      | ^~~~~~~~~~
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:36:1: error: 'PubSubClient' does not name a type; did you mean 'PubSubClient_h'?
   36 | PubSubClient mqtt_client(espClient);              // mqtt client instance
      | ^~~~~~~~~~~~
      | PubSubClient_h
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:38:1: error: 'WiFiEventHandler' does not name a type
   38 | WiFiEventHandler gotIpEventHandler, disconnectedEventHandler;
      | ^~~~~~~~~~~~~~~~
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:44:1: error: 'Ticker' does not name a type
   44 | Ticker tkHeartBeat;                               // Timer for HeartBeat
      | ^~~~~~
In file included from C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:3:
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h: In function 'void WriteLog(String, boolean)':
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:118:18: error: 'dstAdjusted' was not declared in this scope
  118 |     time_t now = dstAdjusted.time(&dstAbbrev);
      |                  ^~~~~~~~~~~
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h: In function 'void ConfigureWifi()':
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:147:3: error: 'WiFi' was not declared in this scope; did you mean 'WiFi_h'?
  147 |   WiFi.mode(WIFI_STA);
      |   ^~~~
      |   WiFi_h
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:147:13: error: 'WIFI_STA' was not declared in this scope
  147 |   WiFi.mode(WIFI_STA);
      |             ^~~~~~~~
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:151:17: error: 'IPAddress' was not declared in this scope; did you mean 'IPAddress_h'?
  151 |     WiFi.config(IPAddress(config.ip[0], config.ip[1], config.ip[2], config.ip[3] ),  IPAddress(config.gateway[0], config.gateway[1], config.gateway[2], config.gateway[3] ) , IPAddress(config.netmask[0], config.netmask[1], config.netmask[2], config.netmask[3] ));
      |                 ^~~~~~~~~
      |                 IPAddress_h
In file included from C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:3:
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h: In function 'void WriteConfig()':
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:162:3: error: 'EEPROM' was not declared in this scope; did you mean 'EEPROM_h'?
  162 |   EEPROM.write(120, 'C');
      |   ^~~~~~
      |   EEPROM_h
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:189:3: error: 'WriteStringToEEPROM' was not declared in this scope
  189 |   WriteStringToEEPROM(164, config.ssid);
      |   ^~~~~~~~~~~~~~~~~~~
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h: In function 'boolean ReadConfig()':
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:232:7: error: 'EEPROM' was not declared in this scope; did you mean 'EEPROM_h'?
  232 |   if (EEPROM.read(120) == 'C' && EEPROM.read(121) == 'F'  && EEPROM.read(122) == 'G' )
      |       ^~~~~~
      |       EEPROM_h
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:251:19: error: 'EEPROM' was not declared in this scope; did you mean 'EEPROM_h'?
  251 |     config.dhcp = EEPROM.read(128);
      |                   ^~~~~~
      |                   EEPROM_h
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:269:19: error: 'ReadStringFromEEPROM' was not declared in this scope
  269 |     config.ssid = ReadStringFromEEPROM(164, 32);
      |                   ^~~~~~~~~~~~~~~~~~~~
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:300:31: error: 'ReadStringFromEEPROM' was not declared in this scope
  300 |     config.mqtt_devicetopic = ReadStringFromEEPROM(1300, 20);
      |                               ^~~~~~~~~~~~~~~~~~~~
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:307:7: error: 'EEPROM' was not declared in this scope; did you mean 'EEPROM_h'?
  307 |       EEPROM.write(index, 0);
      |       ^~~~~~
      |       EEPROM_h
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h: In function 'void HeartBeat()':
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:406:7: error: 'WiFi' was not declared in this scope; did you mean 'WiFi_h'?
  406 |   if (WiFi.status() != WL_CONNECTED)
      |       ^~~~
      |       WiFi_h
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:406:24: error: 'WL_CONNECTED' was not declared in this scope; did you mean 'MQTT_CONNECTED'?
  406 |   if (WiFi.status() != WL_CONNECTED)
      |                        ^~~~~~~~~~~~
      |                        MQTT_CONNECTED
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:420:5: error: 'tkHeartBeat' was not declared in this scope; did you mean 'HeartBeat'?
  420 |     tkHeartBeat.attach(pulse_on, HeartBeat);
      |     ^~~~~~~~~~~
      |     HeartBeat
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/global.h:422:5: error: 'tkHeartBeat' was not declared in this scope; did you mean 'HeartBeat'?
  422 |     tkHeartBeat.attach(pulse_off, HeartBeat);
      |     ^~~~~~~~~~~
      |     HeartBeat
In file included from C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:4:
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/helpers.h: In function 'void WriteStringToEEPROM(int, String)':
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/helpers.h:47:5: error: 'EEPROM' was not declared in this scope; did you mean 'EEPROM_h'?
   47 |     EEPROM.write(beginaddress + t, charBuf[t]);
      |     ^~~~~~
      |     EEPROM_h
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/helpers.h: In function 'String ReadStringFromEEPROM(int, int)':
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/helpers.h:59:13: error: 'EEPROM' was not declared in this scope; did you mean 'EEPROM_h'?
   59 |     rChar = EEPROM.read(beginaddress + counter);
      |             ^~~~~~
      |             EEPROM_h
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/helpers.h: In function 'void EEPROMWritelong(int, long int)':
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/helpers.h:78:3: error: 'EEPROM' was not declared in this scope; did you mean 'EEPROM_h'?
   78 |   EEPROM.write(address, four);
      |   ^~~~~~
      |   EEPROM_h
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/helpers.h: In function 'long int EEPROMReadlong(long int)':
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/helpers.h:88:15: error: 'EEPROM' was not declared in this scope; did you mean 'EEPROM_h'?
   88 |   long four = EEPROM.read(address);
      |               ^~~~~~
      |               EEPROM_h
In file included from C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:5:
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h: In function 'void html_api()':
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h:22:66: error: 'server' was not declared in this scope; did you mean 'server_h'?
   22 |   if (debug_webui) Serial.printf("html_api server.args()=%d \n", server.args());
      |                                                                  ^~~~~~
      |                                                                  server_h
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h:23:7: error: 'server' was not declared in this scope; did you mean 'server_h'?
   23 |   if (server.args() > 0 ) {
      |       ^~~~~~
      |       server_h
In file included from C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:11:
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h: At global scope:
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h:21:6: error: redefinition of 'void html_api()'
   21 | void html_api() {
      |      ^~~~~~~~
In file included from C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:5:
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h:21:6: note: 'void html_api()' previously defined here
   21 | void html_api() {
      |      ^~~~~~~~
In file included from C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:11:
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h: In function 'void html_api()':
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h:22:66: error: 'server' was not declared in this scope; did you mean 'server_h'?
   22 |   if (debug_webui) Serial.printf("html_api server.args()=%d \n", server.args());
      |                                                                  ^~~~~~
      |                                                                  server_h
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h:23:7: error: 'server' was not declared in this scope; did you mean 'server_h'?
   23 |   if (server.args() > 0 ) {
      |       ^~~~~~
      |       server_h
In file included from C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:17:
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h: At global scope:
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h:21:6: error: redefinition of 'void html_api()'
   21 | void html_api() {
      |      ^~~~~~~~
In file included from C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:5:
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h:21:6: note: 'void html_api()' previously defined here
   21 | void html_api() {
      |      ^~~~~~~~
In file included from C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:17:
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h: In function 'void html_api()':
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h:22:66: error: 'server' was not declared in this scope; did you mean 'server_h'?
   22 |   if (debug_webui) Serial.printf("html_api server.args()=%d \n", server.args());
      |                                                                  ^~~~~~
      |                                                                  server_h
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h:23:7: error: 'server' was not declared in this scope; did you mean 'server_h'?
   23 |   if (server.args() > 0 ) {
      |       ^~~~~~
      |       server_h
In file included from C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:74:
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h: At global scope:
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h:21:6: error: redefinition of 'void html_api()'
   21 | void html_api() {
      |      ^~~~~~~~
In file included from C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:5:
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h:21:6: note: 'void html_api()' previously defined here
   21 | void html_api() {
      |      ^~~~~~~~
In file included from C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:74:
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h: In function 'void html_api()':
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h:22:66: error: 'server' was not declared in this scope; did you mean 'Server'?
   22 |   if (debug_webui) Serial.printf("html_api server.args()=%d \n", server.args());
      |                                                                  ^~~~~~
      |                                                                  Server
c:\Users\brank\OneDrive\Dokumente\Arduino\libraries\Jarolift_MQTT-master/html_api.h:23:7: error: 'server' was not declared in this scope; did you mean 'Server'?
   23 |   if (server.args() > 0 ) {
      |       ^~~~~~
      |       Server
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino: In function 'void setup()':
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:156:3: error: 'gotIpEventHandler' was not declared in this scope; did you mean 'WiFiEventHandler'?
  156 |   gotIpEventHandler = WiFi.onStationModeGotIP([](const WiFiEventStationModeGotIP & event)
      |   ^~~~~~~~~~~~~~~~~
      |   WiFiEventHandler
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:162:3: error: 'disconnectedEventHandler' was not declared in this scope
  162 |   disconnectedEventHandler = WiFi.onStationModeDisconnected([](const WiFiEventStationModeDisconnected & event)
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:211:3: error: 'server' was not declared in this scope; did you mean 'Server'?
  211 |   server.on ( "/api", html_api );                       // command api
      |   ^~~~~~
      |   Server
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino: In lambda function:
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:214:25: error: 'server' is not captured
  214 |     if (!handleFileRead(server.uri())) {                // send it if it exists
      |                         ^~~~~~
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:213:22: note: the lambda has no capture-default
  213 |   server.onNotFound([]() {                              // If the client requests any URI
      |                      ^
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:211:3: note: '<typeprefixerror>server' declared here
  211 |   server.on ( "/api", html_api );                       // command api
      |   ^~~~~~
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:215:7: error: 'server' is not captured
  215 |       server.send(404, "text/plain", "404: Not Found"); // otherwise, respond with a 404 (Not Found) error
      |       ^~~~~~
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:213:22: note: the lambda has no capture-default
  213 |   server.onNotFound([]() {                              // If the client requests any URI
      |                      ^
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:211:3: note: '<typeprefixerror>server' declared here
  211 |   server.on ( "/api", html_api );                       // command api
      |   ^~~~~~
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino: In function 'void setup()':
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:222:3: error: 'tkHeartBeat' was not declared in this scope; did you mean 'HeartBeat'?
  222 |   tkHeartBeat.attach(1, HeartBeat);
      |   ^~~~~~~~~~~
      |   HeartBeat
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:225:3: error: 'mqtt_client' was not declared in this scope; did you mean 'mqtt_connect'?
  225 |   mqtt_client.setServer(IPAddress(config.mqtt_broker_addr[0], config.mqtt_broker_addr[1],
      |   ^~~~~~~~~~~
      |   mqtt_connect
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino: In function 'void loop()':
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:263:3: error: 'server' was not declared in this scope; did you mean 'Server'?
  263 |   server.handleClient();
      |   ^~~~~~
      |   Server
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:331:9: error: 'mqtt_client' was not declared in this scope; did you mean 'mqtt_connect'?
  331 |     if (mqtt_client.connected() && mqtt_send_radio_receive_all) {
      |         ^~~~~~~~~~~
      |         mqtt_connect
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:350:12: error: 'mqtt_client' was not declared in this scope; did you mean 'mqtt_connect'?
  350 |       if (!mqtt_client.connected()) {
      |            ^~~~~~~~~~~
      |            mqtt_connect
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino: In function 'bool handleFileRead(String)':
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:653:19: error: 'server' was not declared in this scope; did you mean 'Server'?
  653 |     size_t sent = server.streamFile(file, contentType); // And send it to the client
      |                   ^~~~~~
      |                   Server
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino: In function 'void devcnt_handler(boolean)':
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:743:7: error: 'mqtt_client' was not declared in this scope; did you mean 'mqtt_connect'?
  743 |   if (mqtt_client.connected()) {
      |       ^~~~~~~~~~~
      |       mqtt_connect
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino: In function 'void mqtt_send_percent_closed_state(int, int, String)':
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:758:7: error: 'mqtt_client' was not declared in this scope; did you mean 'mqtt_connect'?
  758 |   if (mqtt_client.connected()) {
      |       ^~~~~~~~~~~
      |       mqtt_connect
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino: In function 'void mqtt_send_config()':
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:776:7: error: 'mqtt_client' was not declared in this scope; did you mean 'mqtt_connect'?
  776 |   if (mqtt_client.connected()) {
      |       ^~~~~~~~~~~
      |       mqtt_connect
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino: In function 'void mqtt_send_config_line(int&, String)':
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:823:3: error: 'mqtt_client' was not declared in this scope; did you mean 'mqtt_connect'?
  823 |   mqtt_client.publish(Topic.c_str(), Payload.c_str());
      |   ^~~~~~~~~~~
      |   mqtt_connect
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino: In function 'void cmd_save_config()':
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:1033:5: error: 'mqtt_client' was not declared in this scope; did you mean 'mqtt_connect'?
 1033 |     mqtt_client.publish(topicOld.c_str(), "", true);
      |     ^~~~~~~~~~~
      |     mqtt_connect
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:1058:7: error: 'server' was not declared in this scope; did you mean 'Server'?
 1058 |       server.send ( 200, "text/plain", "Set new Serial not successful, not a hexadecimal number.");
      |       ^~~~~~
      |       Server
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:1069:3: error: 'server' was not declared in this scope; did you mean 'Server'?
 1069 |   server.send ( 200, "text/plain", "Configuration has been saved, system is restarting. Please refresh manually in about 30 seconds.." );
      |   ^~~~~~
      |   Server
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino: In function 'void cmd_restart()':
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:1077:3: error: 'server' was not declared in this scope; did you mean 'Server'?
 1077 |   server.send ( 200, "text/plain", "System is restarting. Please refresh manually in about 30 seconds." );
      |   ^~~~~~
      |   Server
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino: In function 'boolean mqtt_connect()':
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:1114:7: error: 'mqtt_client' was not declared in this scope; did you mean 'mqtt_connect'?
 1114 |   if (mqtt_client.connect(client_id, username, password, willTopic.c_str(), willQos, willRetain, willMessage )) {
      |       ^~~~~~~~~~~
      |       mqtt_connect
C:\Users\brank\Downloads\Jarolift_MQTT-master\Jarolift_MQTT\Jarolift_MQTT.ino:1123:10: error: 'mqtt_client' was not declared in this scope; did you mean 'mqtt_connect'?
 1123 |   return mqtt_client.connected();
      |          ^~~~~~~~~~~
      |          mqtt_connect

exit status 1

Compilation error: 'gotIpEventHandler' was not declared in this scope; did you mean 'WiFiEventHandler'?
